### ISSUE TITLE
feat. 서버 DB 요청 작성

### ISSUE THREAD

**Issue by L00G** [TryEat/TryEat#10]

**Comment by bokdung** [comment]
[DBdata.txt](https://github.com/TryEat/TryEat/files/1987109/DBdata.txt)

[설계서.zip](https://github.com/TryEat/TryEat/files/1987111/default.zip)

DB CREATE문 DATETIME -> TIMESTAMP 수정, ERD 다이어그램 수정

**Comment by bokdung** [comment]
[DBdata.txt](https://github.com/TryEat/TryEat/files/1997357/DBdata.txt)

[설계서.zip](https://github.com/TryEat/TryEat/files/1997358/default.zip)

DB CREATE문 CASCADE 옵션 추가, 설계서 CREATE문 수정
